language: node_js
node_js:
- '4'
branches:
  only:
  - blog_source
before_install:
- openssl aes-256-cbc -K $encrypted_a27e3e994849_key -iv $encrypted_a27e3e994849_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config user.name "JerryJinJin"
- git config user.email "caijinjin4@gmail.com"
install:
- npm install hexo-cli -g
- npm install hexo-deployer-git --save
- npm install
script:
- hexo clean
- hexo g
after_success:
- hexo deploy
